# Generated by Django 6.0.4 on 2026-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
